PSI NET CORE/Controllers/CitizenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class CitizenController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();

        // GET: Citizen
        public ActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
        public async Task<ActionResult> GetData()
        {
            var data =await unit.CitizenRepository.get();
            var lis = (from a in data select new Citizen {
                Id=a.Id.ToString(),
                FirstName=a.FirstName,
                LastName=a.LastName,
                NationalID=a.NationalID,
                SubLocation=a.SubLocation,
                Location=a.Location,
                Ward=a.Ward,
                County=a.County
            }).ToList();
            return Json(new { data = lis });
        }
        [HttpGet]
        public ActionResult AddorEdit(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return View(new Citizen());
            }
            else
            {
                var data = unit.CitizenRepository.get(Guid.Parse(id));               
                CitizenMapper mapper = new CitizenMapper();
                var citizen = mapper.MapToDomain(data);
                return View(citizen);
            }
        }
        [HttpPost]
        public ActionResult AddorEdit(Citizen ct)
        {
            CitizenMapper mapper = new CitizenMapper();
            var input = mapper.MapToDto(ct);
            if (String.IsNullOrEmpty(ct.Id))
            {
                //insert
                var output= unit.CitizenRepository.insert(input);
                if(output==1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" },new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                //update
                var output = unit.CitizenRepository.update(input.Id,input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }

        }
        [HttpPost]
        public ActionResult Delete(String id)
        {
            var output = unit.CitizenRepository.delete(Guid.Parse(id));
            if (output == 1)
                return Json(new { success = true, message = "Deleted Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
        }

        // POST: Citizen/Delete/5

    }
}

PSI NET CORE/Controllers/OfficerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class OfficerController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();
        OfficerMapper mapper = new OfficerMapper();
        public IActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
        public async Task<ActionResult> GetData()
        {
            var data = await unit.OfficerRepository.get();
            var result= (from t in data select new Officer
            {
                Id = t.Id.ToString(),
                FirstName = t.FirstName,
                LastName = t.LastName,
                NationalID = t.NationalID,
                PostId = t.PostId,
                WorkId = t.WorkId,
                DateEmployed = t.DateEmployed
            }).ToList();
            return Json(new { data = result});
        }
        [HttpGet]
        public IActionResult CreateUpdate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return View(new Officer());

            var data = unit.OfficerRepository.get(Guid.Parse(id));
            var res = mapper.MapToDomain(data);
            return View(res);
        }
        [HttpPost]
        public IActionResult CreateUpdate(Officer t)
        {
            var input = mapper.MapToDto(t);
            if (String.IsNullOrEmpty(t.Id))
            {
                var output = unit.OfficerRepository.insert(input);
                if (output == 1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                var output = unit.OfficerRepository.update(input.Id, input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        [HttpPost]
        public IActionResult Delete(String id)
        {
            var result = unit.OfficerRepository.delete(Guid.Parse(id));
            if (result == 1)
                return Json(new { success = true, message = "Deleted SuccessFully" }, new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new { success = false, message = "Deletion failed" }, new Newtonsoft.Json.JsonSerializerSettings());
        }
    }
}

PSI NET CORE/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class StationController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();
        StationMapper mapper = new StationMapper();
        public IActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
        public async Task<ActionResult> GetData()
        {
            var data = await unit.StationRepository.get();
            var result = (from t in data select new Station{

                Id = t.Id.ToString(),
                StationNo = t.StationNo,
                Name = t.Name,
                Location = t.Location,
                SubLocation = t.SubLocation,
                Ward = t.Ward,
                County = t.County
            }).ToList();
            return Json(new { data = result});
        }
        [HttpGet]
        public IActionResult CreateUpdate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return View(new Station());

            var data = unit.StationRepository.get(Guid.Parse(id));
            var res = mapper.MapToDomain(data);
            return View(res);
        }
        [HttpPost]
        public IActionResult CreateUpdate(Station t)
        {
            var input = mapper.MapToDto(t);
            if (String.IsNullOrEmpty(t.Id))
            {
                var output = unit.StationRepository.insert(input);
                if (output == 1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                var output = unit.StationRepository.update(input.Id, input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        [HttpPost]
        public IActionResult Delete(String id)
        {
            var result = unit.StationRepository.delete(Guid.Parse(id));
            if (result == 1)
                return Json(new { success = true, message = "Deleted SuccessFully" }, new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new { success = false, message = "Deletion failed" }, new Newtonsoft.Json.JsonSerializerSettings());
        }
    }
}

PSI NET CORE/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class WorkController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();
        WorkMapper mapper = new WorkMapper();
        public IActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
        public async Task<ActionResult> GetData()
        {
            var data = await unit.WorkRepository.get();
            var result = (from t in data select new Work {
                Id = t.Id.ToString(),
                Name=t.Name
            }).ToList();
            return Json(new { data = result});
        }
        [HttpGet]
        public ActionResult CreateUpdate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return View(new Work());

            var data = unit.WorkRepository.get(Guid.Parse(id));
            var res=mapper.MapToDomain(data);
            return View(res);
        }
        [HttpPost]
        public ActionResult CreateUpdate(Work t)
        {
            var input=mapper.MapToDto(t);
            if (String.IsNullOrEmpty(t.Id))
            {
                var output = unit.WorkRepository.insert(input);
                if (output == 1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                var output = unit.WorkRepository.update(input.Id, input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        [HttpPost]
        public ActionResult Delete(String id)
        {
            var result = unit.WorkRepository.delete(Guid.Parse(id));
            if (result == 1)
                return Json(new {success=true,message="Deleted SuccessFully" },new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new {success=false,message="Deletion failed" },new Newtonsoft.Json.JsonSerializerSettings());
        }
    }
}

PSI NET CORE/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    var username = HttpContextAccessor.HttpContext.Session.GetString(SessionManager.SessionUserName);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSI_NET_CORE</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    
        <environment exclude="Development">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                  crossorigin="anonymous"
                  integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        </environment>
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
<body>
    @if (username != null)
    {
        <div id="wrapper">

            <div id="sidebar-wrapper" class="navbar-dark bg-faded">
                <ul class="sidebar-nav bg-faded">
                    <li class="sidebar-brand">
                        <a href="#">
                            PSI
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-tachometer" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Dashboard</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Citizen" asp-action="Index"><i class="fa fa-users" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Citizen</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Foreigner" asp-action="Index"><i class="fa fa-users" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Foreigner</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Criminal" asp-action="Index"><i class="fa fa-file" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Criminal</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Suspect" asp-action="Index"><i class="fa fa-file" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Suspect</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Officer" asp-action="Index"><i class="fa fa-gavel" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Officer</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Index"><i class="fa fa-building-o" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Station</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Work" asp-action="Index"><i class="fa fa-diamond" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i> Work</a>
                    </li>

                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout"><i class="fa fa-mobile" style="font-size:26px;padding-right:8px;" aria-hidden="true"></i>Logout</a>
                    </li>
                </ul>
            </div>
            <div class="container">
                    <header>
                        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                            <div class="container">
                                <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars" style="font-size:36px;padding-right:20px;"></i></a>
                                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PSI_NET_CORE</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                                    <ul class="navbar-nav  ml-auto">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Welcome <span class="font-weight-bold text-capitalize">@username </span> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </header>
                    <partial name="_CookieConsentPartial" />
                
                <main role="main" class="pb-3 ">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2021 - PSI_NET_CORE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
    }
    else
    { 
        <div class="container" id="loginPage">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/dataTables.jqueryui.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>

    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"
            integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA="
            crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>