PSI NET CORE/Models/Suspect.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PSI_NET_CORE.Models
{
    public class Suspect
    {
        public String Id { get; set; }
        [Required(ErrorMessage = "National ID is required")]
        [DataType(DataType.Text)]
        [Display(Name = "National ID")]
        public int NationalID { get; set; }

        [Required(ErrorMessage = "Passport is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Passport No")]
        public int PassPortNo { get; set; }

        [Required(ErrorMessage = "Allegation is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Allegation")]
        public String Allegation { get; set; }

        [Required(ErrorMessage = "Discription is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Discription")]
        public String Description { get; set; }

        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public String AllegationDate { get; set; }

    }
}

PSI NET CORE/Controllers/SuspectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class SuspectController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();
        SuspectMapper mapper = new SuspectMapper();
        public IActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }

        public async Task<ActionResult> GetData()
        {
            var data = await unit.SuspectRepository.get();
            var result = (from t in data select new Suspect{
                Id = t.Id.ToString(),
                NationalID = t.NationalID,
                PassPortNo = t.PassPortNo,
                Allegation = t.Allegation,
                Description = t.Description,
                AllegationDate = t.AllegationDate
            }).ToList();
            return Json(new { data =result});
        }
        [HttpGet]
        public IActionResult CreateUpdate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return View(new Suspect());

            var data = unit.SuspectRepository.get(Guid.Parse(id));
            var res = mapper.MapToDomain(data);
            return View(res);
        }
        [HttpPost]
        public IActionResult CreateUpdate(Suspect t)
        {
            var input = mapper.MapToDto(t);
            if (String.IsNullOrEmpty(t.Id))
            {
                var output = unit.SuspectRepository.insert(input);
                if (output == 1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                var output = unit.SuspectRepository.update(input.Id, input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        [HttpPost]
        public IActionResult Delete(String id)
        {
            var result = unit.SuspectRepository.delete(Guid.Parse(id));
            if (result == 1)
                return Json(new { success = true, message = "Deleted SuccessFully" }, new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new { success = false, message = "Deletion failed" }, new Newtonsoft.Json.JsonSerializerSettings());
        }
    }
}

PSI NET CORE/Views/Suspect/Create.cshtml
@model PSI_NET_CORE.Models.Suspect

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Suspect</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NationalID" class="control-label"></label>
                <input asp-for="NationalID" class="form-control" />
                <span asp-validation-for="NationalID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassPortNo" class="control-label"></label>
                <input asp-for="PassPortNo" class="form-control" />
                <span asp-validation-for="PassPortNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Allegation" class="control-label"></label>
                <input asp-for="Allegation" class="form-control" />
                <span asp-validation-for="Allegation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AllegationDate" class="control-label"></label>
                <input asp-for="AllegationDate" class="form-control" />
                <span asp-validation-for="AllegationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSI NET CORE/Views/Suspect/CreateUpdate.cshtml
@model PSI_NET_CORE.Models.Suspect

@{
    Layout = null;
}

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("CreateUpdate", "Suspect", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
        {
            @Html.HiddenFor(model => model.Id)
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NationalID" class="control-label"></label>
                <input asp-for="NationalID" class="form-control" />
                <span asp-validation-for="NationalID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassPortNo" class="control-label"></label>
                <input asp-for="PassPortNo" class="form-control" />
                <span asp-validation-for="PassPortNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Allegation" class="control-label"></label>
                <input asp-for="Allegation" class="form-control" />
                <span asp-validation-for="Allegation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AllegationDate" class="control-label"></label>
                <input asp-for="AllegationDate" class="form-control" />
                <span asp-validation-for="AllegationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
        </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSI NET CORE/Views/Suspect/Index.cshtml
@model IEnumerable<PSI_NET_CORE.Models.Suspect>

@{
    ViewData["Title"] = "Suspect";
}

<h1>Suspect</h1>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("CreateUpdate","Suspect")')"><i class="fa fa-plus"></i> Add New</a>

<table id="Suspecttb" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NationalID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassPortNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Allegation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AllegationDate)
            </th>
            <th></th>
        </tr>
    </thead>
</table>
@section Scripts {
    <script>
        var dataTable, Popup;
        $(document).ready(function () {
            dataTable=$("#Suspecttb").DataTable({
                "ajax": {
                    "url": "/Suspect/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "nationalID" },
                    { "data": "passPortNo" },
                    { "data": "allegation" },
                    { "data": "description" },
                    { "data": "allegationDate" },
                    {"data":"id" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("CreateUpdate", "Suspect")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm js-delete' data-citizen-id=" + data + " style='margin-left:5px'><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }
                ],
                "language": {
                    "emptyTable": "No data Found, Please click on <b> Add New </b> Button"
                }


            });

        });

        //update/Edit popup
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Fill Suspect Details',
                        height: 510,
                        width: 700,
                        background: '#808080',
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        //update/insert form submission
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                        else {
                            Popup.dialog('close');
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "danger"
                            })
                        }
                    }
                });
            }
            return false;
        }
        //deletion
        $("#Suspecttb").on("click", ".js-delete", function () {
            var button = $(this);
            bootbox.confirm("Are you sure you want to delete?", function (result) {
                if (result) {
                    $.ajax({
                        url: "/Suspect/Delete/" + button.attr("data-citizen-id"),
                        method: "POST",
                        success: function (data) {
                            if (data.success) {
                                dataTable.row(button.parents("tr")).remove().draw();
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "success"
                                });
                            }
                            else {
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "alert-info"
                                });
                            }
                        }
                    });
                }

            });
        });
    </script>
}