PSI NET CORE/Models/Foreigner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace PSI_NET_CORE.Models
{
    public class Foreigner
    {
        public String Id { get; set; }
        [Required(ErrorMessage = "Firstname is required")]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        public String FirstName { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        public String LastName { get; set; }


        [Required(ErrorMessage = "Passport is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Passport No")]
        public int PassPortNo { get; set; }


        [Required(ErrorMessage = "City is required")]
        [DataType(DataType.Text)]
        [Display(Name = "City")]
        public String City { get; set; }


        [Required(ErrorMessage = "Country is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Country")]
        public String Country { get; set; }


        [Required(ErrorMessage = "Date In is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Date IN")]
        public String DateIn { get; set; }


        [Required(ErrorMessage = "Date Out is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Date Out")]
        public String DateOut { get; set; }
    }
}

PSI NET CORE/Controllers/ForeignerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSI_NET_CORE.Models;
using PSI_NET_CORE.Network.Mappers;
using PSI_NET_CORE.Network.Repo;

namespace PSI_NET_CORE.Controllers
{
    public class ForeignerController : Controller
    {
        private UnitOfWork unit = new UnitOfWork();
        ForeignerMapper mapper = new ForeignerMapper();
        public ActionResult Index()
        {
            var sess = HttpContext.Session.GetString(SessionManager.SessionUserName);
            if (sess == null)
            {
                return RedirectToAction("Index", "Auth");
            }
            return View();
        }
        public async Task<ActionResult> GetData()
        {
            var data = await unit.ForeignerRepository.get();
            var foreigners = (from t in data select new Foreigner
            {
                Id = t.Id.ToString(),
                FirstName = t.FirstName,
                LastName = t.LastName,
                PassPortNo = t.PassPortNo,
                City = t.City,
                Country = t.Country,
                DateIn = t.DateIn,
                DateOut = t.DateOut
            }).ToList();
            return Json(new { data = foreigners });
        }
        [HttpGet]
        public IActionResult CreateUpdate(string id)
        {
            if (String.IsNullOrEmpty(id))
                return View(new Foreigner());

            var data = unit.ForeignerRepository.get(Guid.Parse(id));
            var res = mapper.MapToDomain(data);
            return View(res);
        }
        [HttpPost]
        public IActionResult CreateUpdate(Foreigner t)
        {
            var input = mapper.MapToDto(t);
            if (String.IsNullOrEmpty(t.Id))
            {
                var output = unit.ForeignerRepository.insert(input);
                if (output == 1)
                    return Json(new { success = true, message = "Added Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
            else
            {
                var output = unit.ForeignerRepository.update(input.Id, input);
                if (output == 1)
                    return Json(new { success = true, message = "Updated Successfully" }, new Newtonsoft.Json.JsonSerializerSettings());
                return Json(new { success = false, message = "process failed" }, new Newtonsoft.Json.JsonSerializerSettings());
            }
        }

        [HttpPost]
        public IActionResult Delete(String id)
        {
            var result = unit.ForeignerRepository.delete(Guid.Parse(id));
            if (result == 1)
                return Json(new { success = true, message = "Deleted SuccessFully" }, new Newtonsoft.Json.JsonSerializerSettings());
            return Json(new { success = false, message = "Deletion failed" }, new Newtonsoft.Json.JsonSerializerSettings());
        }
    }
}

PSI NET CORE/Views/Foreigner/Create.cshtml
@model PSI_NET_CORE.Models.Foreigner

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Foreigner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassPortNo" class="control-label"></label>
                <input asp-for="PassPortNo" class="form-control" />
                <span asp-validation-for="PassPortNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateIn" class="control-label"></label>
                <input asp-for="DateIn" class="form-control" />
                <span asp-validation-for="DateIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOut" class="control-label"></label>
                <input asp-for="DateOut" class="form-control" />
                <span asp-validation-for="DateOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSI NET CORE/Views/Foreigner/CreateUpdate.cshtml
@model PSI_NET_CORE.Models.Foreigner

@{
    Layout = null;
}

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("CreateUpdate", "Foreigner", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
        {
            @Html.HiddenFor(model => model.Id)
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassPortNo" class="control-label"></label>
                <input asp-for="PassPortNo" class="form-control" />
                <span asp-validation-for="PassPortNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateIn" class="control-label"></label>
                <input asp-for="DateIn" class="form-control" />
                <span asp-validation-for="DateIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOut" class="control-label"></label>
                <input asp-for="DateOut" class="form-control" />
                <span asp-validation-for="DateOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
        </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSI NET CORE/Views/Foreigner/Index.cshtml
@model IEnumerable<PSI_NET_CORE.Models.Foreigner>

@{
    ViewData["Title"] = "Foreigner";
}

<h1>Foreigner</h1>
<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("CreateUpdate","Foreigner")')"><i class="fa fa-plus"></i> Add New</a>

<table id="Foreignertb" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassPortNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOut)
            </th>
            <th></th>
        </tr>
    </thead>
</table>
@section Scripts {
    <script>
        var dataTable, Popup;
        $(document).ready(function () {
            dataTable= $("#Foreignertb").DataTable({
                "ajax": {
                    "url": "/Foreigner/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "firstName" },
                    { "data": "lastName" },
                    { "data": "passPortNo" },
                    { "data": "city" },
                    { "data": "country" },
                    { "data": "dateIn" },
                    { "data": "dateOut" },
                    {"data":"id" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("CreateUpdate", "Foreigner")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm js-delete' data-citizen-id=" + data + " style='margin-left:5px'><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }
                ],
                "language": {
                    "emptyTable": "No data Found, Please click on <b> Add New </b> Button"
                }


            });

        });

        //update/Edit popup
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Fill Foreigner Details',
                        height: 500,
                        width: 700,
                        background: '#808080',
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        //update/insert form submission
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                        else {
                            Popup.dialog('close');
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "danger"
                            })
                        }
                    }
                });
            }
            return false;
        }
        //deletion
        $("#Foreignertb").on("click", ".js-delete", function () {
            var button = $(this);
            bootbox.confirm("Are you sure you want to delete?", function (result) {
                if (result) {
                    $.ajax({
                        url: "/Foreigner/Delete/" + button.attr("data-citizen-id"),
                        method: "POST",
                        success: function (data) {
                            if (data.success) {
                                dataTable.row(button.parents("tr")).remove().draw();
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "success"
                                });
                            }
                            else {
                                $.notify(data.message, {
                                    globalPosition: "top center",
                                    className: "alert-info"
                                });
                            }
                        }
                    });
                }

            });
        });
    </script>
}